package com.example.quizapp

class ListOfWords {
    val words = listOf(
        "Aceh",
        "Sumatera/Utara",
        "Sumatera/Selatan",
        "Sumatera/Barat",
        "Bengkulu",
        "Riau",
        "Kepulauan/Riau",
        "Jambi",
        "Lampung",
        "Bangka/Belitung",
        "Kalimantan/Barat",
        "Kalimantan/Timur",
        "Kalimantan/Selatan",
        "Kalimantan/Tengah",
        "Kalimantan/Utara",
        "Banten",
        "DKI/Jakarta",
        "Jawa/Barat",
        "Jawa/Tengah",
        "Jawa/Timur",
        "Yogyakarta",
        "Bali",
        "NTT",
        "NTB",
        "Gorontalo",
        "Sulawesi/Barat",
        "Sulawesi/Tengah",
        "Sulawesi/Utara",
        "Sulawesi/Tenggara",
        "Sulawesi/Selatan",
        "Maluku/Utara",
        "Maluku",
        "Papua",
        "Papua/Barat",
        "Papua/Tengah",
        "Papua/Pegunungan",
        "Papua/Selatan",
        "Papua/Barat/Daya"
    )
}